### ISSUE TITLE
No 'ios' folder in current package installed via yarn or npm

### ISSUE THREAD

**Issue by lucaronca** [Aminoid/react-native-activity-recognition#3]
I installed this module both with yarn and npm and currently i doesn't see the ios folder inside `node_modules/react-native-activity-recognition`, maybe the latest updates were not published on npm?

**Comment by ghengeveld** [comment]
Correct. We are in the process of transferring ownership to @Aminoid. He already has rights to publish a new version to npm, but apparently he hasn't done so yet. For now you can depend on the git repo directly (`XebiaStudio/react-native-activity-recognition`).

**Comment by ghengeveld** [comment]
Should be resolved now. 🎉

**Comment by Aminoid** [comment]
Hi @lucaronca as pointed out by @ghengeveld, this should be resolved via version 3.1.0
